### ISSUE TITLE
Demo Offline

### ISSUE THREAD

**Issue by IgorDePaula** [jhonmike/Zf2SkeletonApp#3]
Demo Offline

**Comment by jhonmike** [comment]
Mudei a hospedagem, e tambem não estou conseguindo manter o projeto sozinho, preciso de ajuda pra melhorar mais o projeto!

**Comment by IgorDePaula** [comment]
Desculpe perguntar, mas eu nao entendi muito bem o objetivo do projeto.

**Comment by jhonmike** [comment]
esse projeto eu iniciei a mais de ano quando estava aprendendo zend 2, eu criei um padrao para trabalhar com zend 2 e doctrine 2, que estava usando ate novembro do ano passado, agora estou trabalhando com outro padrao de projetos onde uso o APIgility do Zend 2, e AngularJS, mais sempre q der vou tentar melhorar ainda esse projeto, pois varias pessoas jah entraram em contato q começaram a usar esse padrao de projeto que criei de usuario, authenticação e autorização pela ACL, e acharam facil, tem varios exemplos na net parecido com esse padrao, e eu em particular nao melhorem muito pq sempre foi o suficiente pra mim usar de ponto de partida dos meus projetos, soh agora que decidi evoluir para o apigility e o angularjs por questões de usabilidade e interaçao com o usuario.

**Comment by IgorDePaula** [comment]
AngularJS eh fantastico...eu prefiro suar ele com nodejs/expressjs e mongo,
nao acho o apigility tao usual assim...enfim...sua estrutura esta muito
boa. Eu perguntei porque voce disse estar sozinho pra tocar o projeto e eu
estou com um projeto parecido, com um objetivo um pouco diferente:
construir uma base, e esta base instalar plugin onde cada plugin seria uma
aplicacao diferente, gestor de projetos, helpdesk etc.

Em 28 de janeiro de 2015 20:01, Jhon Mike <notifications@github.com>
escreveu:

**Comment by jhonmike** [comment]
Sim angularjs com nodejs e mongo fica perfeito, mais tive alguns detalhes q me levaram para o apigility, skype: jhonmike14, emails: developer@jhonmike.com.br ou jhonmike@hotmail.com.br, me manda os links do github de seu projeto, vou dar uma olhada e se possivel estarei fazendo o maximo possivel para contribuir com seus repositorios.

**Comment by IgorDePaula** [comment]
Eu comecei estes 2: Collab-Z (https://github.com/collab-z) e Help-Z (
https://github.com/Help-Z), e ainda pensei no ERP-Z. Tudo open source para
que outras pessoas possam criar outros modulos e plugins. O Collab-z seria
um gestor de projetos com módulos para scrum e baseados no PMBOK. O Help-z
seria um helpdesk para profissionais de TI baseado em alguns no mercado e
algumas solicitacoes de amigos e experiencia profissional. Eu tinha
começado o help-z e percebi que ambos usariam a mesma base entao porque não
construir módulos que instalados sobre uma base montaria-se um sistema ? Se
a pessoa quiser um ERP ela instala os modulos do ERP, se ela quiser o
helpdesk, ela instala os modulos do helpdesk Eu já comecei e como você
também tenho pouco tempo. Eu enxuguei agora porque diminui os sistemas em
numero, mas não em módulos. A ideia é devagar e sempre sem perder o fio da
meada, sem desistir, mesmo que seja uma hora mas com a missão de uma
feature terminada e funcional. Esse projetão ainda não dei um nome se tiver
alguma sugestão...

Skype: in.luar / espiritodocoracao@hotmail.com
email: principe.borodin@gmail.com

Em 29 de janeiro de 2015 21:44, Jhon Mike <notifications@github.com>
escreveu:
