### ISSUE TITLE
localhost

### ISSUE THREAD

**Issue by eponcehenriquez** [jhonmike/Zf2SkeletonApp#4]
pesaroso para meus portuges

mas para fazer logon no http://localhost/final/public/ nome de usuário e senha e digite me redirecionado para http: //localhost/auth não encontrar o caminho, eu mudei algumas coisas na sua falta resolver esse problema, eu poderia ajudar, cumprimentos e agradeço antecipadamente

**Comment by jhonmike** [comment]
Resolvido: be169e503c96ffd30ddb41f4787ad017320e665a

Desculpe pelo transtorno e obrigado por avisar!

Obs.: se estiver usando Apache tente configurar uma VirtualHost!

**Comment by eponcehenriquez** [comment]
muito obrigado, eu tinha resolvido e eu aprontaba para comunicá-lo.

saudações e agradecimentos
